name: RFC workflow

on:
  issues:
    types: [opened, edited]
    
jobs:
  rfc-check:

    runs-on: ubuntu-latest

    steps:
      - name: Collect issues
        uses: mark43/github-actions/collect-issues@v1
        id: collect_issues        
        with:
          repo-token: '"${{ secrets.GITHUB_TOKEN }}"'
          titlefilters: '["^RFC"]'
          labelfilters: '["rfc/.*"]'
          env-output-variable: '"ISSUE_NUMBER_OUTPUT"'
      - name: Output test
        run: |
          echo 'env variable:'
          echo $ISSUE_NUMBER_OUTPUT
          echo '------'
          echo 'output:'
          echo ${{ steps.collect_issues.outputs.issue_numbers }}
      - name: Send to slack
        uses: mark43/github-actions/slack-messages@slack-messages-v1
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          default-conversation-id: ${{ secrets.CONVERSATION_ID }}
          messages: '{"mrkdwn":true,"text":"found issues  *${{ steps.collect_issues.outputs.issue_numbers }}*"}'
