name: RFC workflow

on:
  issues:
    types: [opened, edited]
    
jobs:
  rfc-check:

    runs-on: ubuntu-latest

    steps:
      - name: Collect issues
        uses: mark43/github-actions/collect-issues@v1
        with:
          repo-token: '"${{ secrets.GITHUB_TOKEN }}"'
          titlefilters: '["testing"]'
          labelfilters: '[]'
          env-output-variable: '"ID_OUTPUT"'
      - name: Output test
        run: |
          echo 'env variable:'
          echo $ID_OUTPUT
          echo '------'
          echo 'output:'
          echo ${{ steps.collect_issues.outputs.issueids }}
