name: RFC workflow

on:
  issues:
    types: [opened, edited]
    
jobs:
  rfc-check:

    runs-on: ubuntu-latest

    steps:
      - name: Collect issues
        uses: mark43/github-actions/collect-issues@v1
        id: collect_issues        
        with:
          repo-token: '"${{ secrets.GITHUB_TOKEN }}"'
          titlefilters: '["^RFC"]'
          labelfilters: '["rfc/.*"]'
          env-output-variable: '"ISSUE_NUMBER_OUTPUT"'
      - name: Create RFC digest
        uses: mark43/github-actions/create-rfc-digest@create-rfc-digest-v1
        id: create_rfc_digest
        with:
          issue_numbers: ${{ steps.collect_issues.outputs.issue_numbers }} 
      - name: Send to slack
        uses: mark43/github-actions/slack-messages@slack-messages-v1
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          default-conversation-id: ${{ secrets.CONVERSATION_ID }}
          messages: ${{ steps.create_rfc_digest.outputs.rfc_digest_message_json }}
